#include "arp.h"
#include "arpcache.h"
#include "icmp.h"
#include "ip.h"
#include "rtable.h"

// #include "log.h"

#include <assert.h>
#include <stdio.h>
#include <stdlib.h>

#define FILTER 0x80000000

// initialize ip header
void ip_init_hdr(struct iphdr *ip, u32 saddr, u32 daddr, u16 len, u8 proto) {
  ip->version = 4;
  ip->ihl = 5;
  ip->tos = 0;
  ip->tot_len = htons(len);
  ip->id = rand();
  ip->frag_off = htons(IP_DF);
  ip->ttl = DEFAULT_TTL;
  ip->protocol = proto;
  ip->saddr = htonl(saddr);
  ip->daddr = htonl(daddr);
  ip->checksum = ip_checksum(ip);
}

// lookup in the routing table,
// to find the entry with the same and longest prefix.
// the input address is in host byte order
rt_entry_t *longest_prefix_match(u32 dst) {
  // OK
  // longest prefix match for the packet

  rt_entry_t *pos_rt, *q_rt;
  u32 max_match = 0;
  rt_entry_t *found = NULL;
  // traverse rtable
  list_for_each_entry_safe(pos_rt, q_rt, &rtable, list) {
    u32 match = pos_rt->mask;
    // if it is possible to get longest match
    if (match > max_match) {
      // if match
      if ((dst & match) == (pos_rt->dest & match)) {
        max_match = match;
        found = pos_rt;
      }
    }
  }
  return found;
}

// send IP packet
//
// Different from forwarding packet,
// ip_send_packet sends packet generated by router itself.
// This function is used to send ICMP packets.
void ip_send_packet(char *packet, int len) {
  // OK
  // send ip packet

  struct iphdr *ih = packet_to_ip_hdr(packet);
  // EXTRACT DEST IP
  u32 dest = ntohl(ih->daddr);
  // FIND LONGEST MATCH RTABLE ITEM
  rt_entry_t *r = longest_prefix_match(dest);
  if (r == NULL) {
    fprintf(stderr, "WARNING: check your rtable-related functions.\n");
  } else {
    ih->saddr = htonl(r->iface->ip);
    ih->checksum = ip_checksum(ih);
    u32 nxt_hop = (r->gw == 0) ? dest : r->gw;
    // FORWARD
    iface_send_packet_by_arp(r->iface, nxt_hop, packet, len);
  }
}
